### PR TITLE
Update to Ember 3.15

### PR DESCRIPTION
**Pull request by bobisjan**
- update project using `ember-cli-update`
- drop support for Node.js < 8 💥
- drop support for Ember.js < 3.8 💥

### CODE REVIEW

**Comment by bobisjan** [comment]
@willviles, can you please take a look? ☺️

**Comment by kmccullough** [comment]
Thanks @bobisjan! I was getting an error from babel without this fix.

**Comment by bobisjan** [comment]
@willviles, friendly reminder if you can take a look, thanks ☺️

**Comment by willviles** [comment]
Sorry it took a while @bobisjan!

**Comment by bobisjan** [comment]
@willviles, no problem ☺️, I'm going to rebase reaming PRs with FastBoot.

**Comment by willviles** [comment]
@bobisjan thanks for all of your efforts. Released in `0.10.0`!

**Pull request merged**
